# Generated by Django 3.1.7 on 2021-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='subtitle',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
