# Generated by Django 3.1.7 on 2021-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_form_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
