# Generated by Django 3.1.7 on 2021-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210327_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
