# Generated by Django 3.1.7 on 2021-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='subject',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
