# Generated by Django 3.1.7 on 2021-06-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210410_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Form contact person',
                'verbose_name_plural': 'Form contact people',
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='country',
            field=models.IntegerField(choices=[(1, 'Germany'), (2, 'Spain')], default=1),
        ),
        migrations.AddField(
            model_name='form',
            name='style',
            field=models.IntegerField(choices=[(1, 'Style A'), (2, 'Style B')], default=1),
        ),
        migrations.AddField(
            model_name='form',
            name='thank_you_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='contact_people',
            field=models.ManyToManyField(blank=True, to='core.FormContactPerson'),
        ),
    ]
