# Generated by Django 3.1.7 on 2021-06-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210603_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='thank_you_page',
            new_name='external_thank_you_page',
        ),
    ]
