# Generated by Django 3.1.7 on 2021-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210603_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_style_b',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
