# Generated by Django 3.1.7 on 2021-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answer_image_style_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contact_form_button_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='form',
            name='contact_form_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='form',
            name='privacy_policy_text',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
