# Generated by Django 3.1.7 on 2021-11-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211125_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='privacy_policy_text',
            new_name='brand_name',
        ),
    ]
