# Generated by Django 3.1.7 on 2021-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211125_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image_style_b',
        ),
        migrations.RemoveField(
            model_name='form',
            name='country',
        ),
        migrations.AlterField(
            model_name='form',
            name='style',
            field=models.IntegerField(choices=[(1, 'Style A')], default=1),
        ),
    ]
