# Generated by Django 3.1.7 on 2021-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211126_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
