# Generated by Django 3.1.7 on 2022-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220203_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='adgroup',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='keyword',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
