# Generated by Django 3.1.7 on 2021-12-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211202_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created', 'first_name', 'last_name'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
