# Generated by Django 3.1.7 on 2022-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211217_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='language',
            field=models.IntegerField(choices=[(1, 'France'), (2, 'Belgium')], default=1),
        ),
    ]
