# Generated by Django 3.1.7 on 2022-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211217_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
