# Generated by Django 3.1.7 on 2021-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211217_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('man', 'Monsieur'), ('women', 'Madame')], default='man', max_length=5),
        ),
    ]
