# Generated by Django 3.1.7 on 2022-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_question_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Espacial'),
        ),
    ]
