# Generated by Django 3.1.7 on 2022-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_form_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.IntegerField(choices=[('fr', 'Français'), ('nl', 'Nederlands')], default='fr'),
        ),
    ]
