# Generated by Django 3.1.7 on 2021-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lead_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contact_form_subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
