# Generated by Django 3.1.7 on 2022-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220126_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='special2',
            field=models.BooleanField(default=False, verbose_name='Ubicación escalera'),
        ),
        migrations.AlterField(
            model_name='question',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Tipo escalera'),
        ),
    ]
