# Generated by Django 3.1.7 on 2021-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_form_contact_form_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contact_form_subtitle',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
