# Generated by Django 3.1.7 on 2022-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220111_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands')], default='fr', max_length=3),
        ),
    ]
