# Generated by Django 3.1.7 on 2022-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220126_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
