# Generated by Django 3.1.7 on 2022-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220111_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.IntegerField(choices=[(1, 'Short'), (2, 'Normal')], default=2),
        ),
    ]
