# Generated by Django 3.1.7 on 2022-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lead_gclid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contact_subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='form',
            name='contact_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
