# Generated by Django 3.1.7 on 2025-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_added_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
