# Generated by Django 3.1.7 on 2023-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lead_gclid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.IntegerField(choices=[(1, 'standard'), (2, 'booking')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='calendar_type',
            field=models.BooleanField(default=False, verbose_name='Es de tipo calendario'),
        ),
        migrations.AddField(
            model_name='question',
            name='postal_code_type',
            field=models.BooleanField(default=False, verbose_name='Es de tipo código postal'),
        ),
    ]
