# Generated by Django 3.1.7 on 2022-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Home elevator'), (2, 'Stairlift'), (3, 'Platform lift')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands')], default='fr', max_length=3),
        ),
    ]
