# Generated by Django 3.1.7 on 2022-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220223_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
