# Generated by Django 3.1.7 on 2022-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220523_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contact_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='contact_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
