# Generated by Django 3.1.7 on 2023-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230225_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='lead',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
