# Generated by Django 3.1.7 on 2022-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220524_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
