# Generated by Django 3.1.7 on 2024-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lead_gclid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'GERMAN')], default='fr', max_length=3),
        ),
    ]
