# Generated by Django 3.1.7 on 2023-03-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230225_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='thank_you_image',
            field=models.ImageField(blank=True, null=True, upload_to='thankyou/'),
        ),
        migrations.AddField(
            model_name='form',
            name='thank_you_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='form',
            name='thank_you_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
