# Generated by Django 3.1.7 on 2022-06-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220524_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='contact_subtitle',
        ),
        migrations.RemoveField(
            model_name='form',
            name='contact_title',
        ),
    ]
