# Generated by Django 3.1.7 on 2022-09-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220601_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='add_gtm',
            field=models.BooleanField(default=False),
        ),
    ]
