# Generated by Django 3.1.7 on 2023-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230324_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='add_gtm',
            field=models.BooleanField(default=False),
        ),
    ]
