# Generated by Django 3.1.7 on 2024-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20240307_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'German')], default='fr', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'German')], default='fr', max_length=3),
        ),
    ]
