# Generated by Django 4.2 on 2023-05-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_form_add_gtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_question_count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form')),
            ],
            options={
                'verbose_name': 'Question Progress',
                'verbose_name_plural': 'Question Progress',
            },
        ),
    ]
