# Generated by Django 3.1.7 on 2022-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_form_add_gtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='thankyoupage_out',
            field=models.BooleanField(default=False),
        ),
    ]
