# Generated by Django 3.1.7 on 2022-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_form_add_gtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contact_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='contact_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
