# Generated by Django 3.1.7 on 2025-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_form_thankyoupage_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
