# Generated by Django 3.1.7 on 2023-11-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220929_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='accept_privacy_policy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('Connecticut', 'Connecticut'), ('New Jersey', 'New Jersey'), ('New York', 'New York'), ('Virginia', 'Virginia'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(default=4, max_length=16),
            preserve_default=False,
        ),
    ]
  