# Generated by Django 3.1.7 on 2023-11-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20231116_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='accept_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='zip_code',
        ),
    ]
