# Generated by Django 3.1.7 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_lead_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gvipimo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='msclkid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='mvipimo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]