# Generated by Django 3.1.7 on 2023-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20231122_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.AlterField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(default='00', max_length=16),
        ),
    ]
