# Generated by Django 3.1.7 on 2023-11-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20231122_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='accept_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='zip_code',
        ),
    ]
