# Generated by Django 3.1.7 on 2023-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20231122_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
