# Generated by Django 3.1.7 on 2023-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20231122_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('Connecticut', 'Connecticut'), ('New Jersey', 'New Jersey'), ('New York', 'New York'), ('Virginia', 'Virginia'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(max_length=16),
        ),
    ]
