# Generated by Django 3.1.7 on 2024-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20231122_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='enable_hear_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='hear_from',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
