# Generated by Django 3.1.7 on 2023-11-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20231122_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='postal_code',
        ),
    ]
