# Generated by Django 3.1.7 on 2023-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20231124_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
