# Generated by Django 3.1.7 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lead_additional_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='accept_privacy_policy',
            field=models.BooleanField(),
        ),
    ]
